const SET_NUMBER_OF_PLAYERS = "SET_NUMBER_OF_PLAYERS";
const DEAL = "DEAL";
const UPDATE_DECK = "UPDATE_DECK";
const UPDATE_PLAYERS = "UPDATE_PLAYERS";
const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";
const SET_GAME_STATE = "SET_GAME_STATE";
const READY_TO_DEAL = "READY_TO_DEAL";
const CREATING_CRIB = "CREATING_CRIB";

export {
    SET_NUMBER_OF_PLAYERS,
    DEAL,
    UPDATE_DECK,
    UPDATE_PLAYERS,
    UPDATE_GAME_STATE,
    SET_GAME_STATE,
    READY_TO_DEAL,
    CREATING_CRIB
};
